replicaCount: 1


# autoscaling:
#   enabled: true
#   minReplicas: 1
#   maxReplicas: 10  # Define max number of pods
#   targetCPUUtilizationPercentage: 80 # Trigger scaling when CPU usage reaches 80%
  # You can also use targetMemoryUtilizationPercentage if you want to scale based on memory

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10  # Define max number of pods
  targetMemoryUtilizationPercentage: 70


image:
  repository: sparrowapi/sparrow-api   #shindepratikk/sparrow-api | sparrowapi.azurecr.io/sparrow-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  enabled: true                      # Enables the service
  type: ClusterIP                     # Service type
  port: 80                            # Port to expose
  targetPort: 9000                   # Port the container listens on
  labels:                             # Additional labels for the service
    run: sparrow-api                  # Custom label


livenessProbe:
  enabled: true  # Set to false to disable liveness probe
  port: 9000
  initialDelaySeconds: 40  # Adjust as necessary
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true  # Set to false to disable readiness probe
  port: 9000
  initialDelaySeconds: 15  # Adjust as necessary
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1


ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  enabled: true
  requests:
    # cpu: 100m
    memory: 1024Mi
  limits:
    # cpu: 150m
    memory: 1648Mi
#   # enabled: true
#   requests:
#     cpu: 100m           # Minimum CPU guaranteed to the pod
#     memory: 350Mi       # Increased minimum memory guaranteed to the pod
#   limits:
#     cpu: 500m           # Maximum CPU the pod can use
#     memory: 1500Mi      # Maximum memory the pod can use

  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  
  

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

secrets:
  PORT: "9000"
  APP_ENV: "DEV"
  APP_UPDATE_AVAILABLE : "true"
  APP_URL : "https://dev-api.sparrow.techdomeaks.com"
  APP_VERSION : "2.11.0"
  AZURE_CONNECTION_STRING : "DefaultEndpointsProtocol=https;AccountName=sparrowassets;AccountKey=N7I6yZV7qV8J1B2UZTCKXGgPo6hI5VVbPJDk6Z4oeuBzITguuRbTtzAiiC+FzRPhYUa5JCkNTCfw+AStM8jPRQ==;EndpointSuffix=core.windows.net"
  AZURE_INSIGHTS_CONNECTION_STRING : "InstrumentationKey=a1a41bff-dd46-494c-8da5-16deca5daf32;IngestionEndpoint=https://centralindia-0.in.applicationinsights.azure.com/;LiveEndpoint=https://centralindia.livediagnostics.monitor.azure.com/;ApplicationId=79949c18-deba-4d2e-8ab5-00c1f2496b56"
  AZURE_OPENAI_API_KEY : "91e4e4eb766c4518a24198d699600735"
  AZURE_OPENAI_API_VERSION : "2024-02-15-preview"
  AZURE_OPENAI_DEPLOYMENT : "sparrow"
  AZURE_OPENAI_ENDPOINT : "https://sparrow-app.openai.azure.com/"
  AZURE_OPENAI_MAX_TOKENS : "1000"
  AZURE_OPENAI_MONTHLY_TOKEN_LIMIT : "15000"
  DB_URL : "mongodb://root:NFaBUVIvqj@my-mongodb.sparrow-test.svc.cluster.local/"
  EMAIL_VALIDATION_CODE_EXPIRY_TIME : "604800"
  FEEDBACK_BLOB_CONTAINER : "feedbackfilesdev"
  GOOGLE_ACCESS_TYPE : "offline"
  GOOGLE_APP_URL : "https://dev-api.sparrow.techdomeaks.com"
  GOOGLE_CLIENT_ID : "1068024020574-3v65mvlccj7vg19qfo0g2o00pok7sek8.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET : "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"
  HUBSPOT_BASEURL : "https://api.hsforms.com"
  HUBSPOT_FORMID : "c3f6097b-b6a4-486a-8e60-ddd7dbefe535"
  HUBSPOT_INTEGRATION_ENABLED : "false"
  HUBSPOT_PORTALID : "47180514"
  JWT_EXPIRATION_TIME : "21600"
  JWT_SECRET_KEY : "uAsBw6WxqD"
  KAFKA_BROKER : "my-kafka.sparrow-test.svc.cluster.local:9092"
  LOGIN_REDIRECT_URL : "https://identity-dev.sparrowapp.dev/redirect"
  MAC_APPLE_SILICON_APP_SIGNATURE : dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVRSE1HWmJrS1Q4SzFkN2g5QVB1RS94aEY0NFJsYTZqWnpDMk9LMlVBMis4QSt6RTljcVNBSEsyL3NFL0doeVVFalVXUjFPTENRRlFsRjdzbWVad21zdTFGQU9MQlFzd1FRPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzIxMzgwMjk0CWZpbGU6U3BhcnJvdy5hcHAudGFyLmd6CnFaQ1NJMWpHdXVMUWhXNktYYlh1VHpNU1JkSEY2R3RsZDgvZ3VFNnB3TUJ4VWIrT2hWUjhaZTVBclN3TW0rZ3AxTncxb256eHFjbXdmU1l1cGsxVkRRPT0K
  MAC_APPLE_SILICON_APP_URL : https://sparrow-release-assests-dev.s3.us-west-1.amazonaws.com/Sparrow.app.tar.gz
  MAC_INTEL_APP_SIGNATURE : dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVRSE1HWmJrS1Q4SzFkN2g5QVB1RS94aEY0NFJsYTZqWnpDMk9LMlVBMis4QSt6RTljcVNBSEsyL3NFL0doeVVFalVXUjFPTENRRlFsRjdzbWVad21zdTFGQU9MQlFzd1FRPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzIxMzgwMjk0CWZpbGU6U3BhcnJvdy5hcHAudGFyLmd6CnFaQ1NJMWpHdXVMUWhXNktYYlh1VHpNU1JkSEY2R3RsZDgvZ3VFNnB3TUJ4VWIrT2hWUjhaZTVBclN3TW0rZ3AxTncxb256eHFjbXdmU1l1cGsxVkRRPT0K
  MAC_INTEL_APP_URL : https://sparrow-release-assests-dev.s3.us-west-1.amazonaws.com/Sparrow.app.tar.gz
  REFRESH_TOKEN_EXPIRATION_TIME : "604800"
  REFRESH_TOKEN_MAX_LIMIT : "5"
  REFRESH_TOKEN_SECRET_KEY : "secret"
  SMTP_MAIL_HOST : "smtp.sendgrid.net"
  SMTP_MAIL_PORT : "465"
  SMTP_MAIL_SECURE : "true"
  SMTP_SENDER_EMAIL : "no-reply@sparrowapp.dev"
  SMTP_SENDER_PASSWORD : "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"
  SMTP_USER_NAME : "apikey"
  SPARROW_EMAIL : "contactus@sparrowapp.dev"
  WINDOWS_APP_SIGNATURE : "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVRSE1HWmJrS1Q4SzQvUnpPbWtGTmkrdk45Ky9FTkNkVm51VUlxK1BTbU56bEV4NjBpOURGRWJZem12cnZ1cGF0RUY0b1BTRUlaTHZMN0oyMzFlb0MrQ3lpUUYrQlJnT0FRPQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNzMxMDY4NjgxCWZpbGU6U3BhcnJvd18yLjExLjBfeDY0X2VuLVVTLm1zaS56aXAKYmlSSUJXUVJnMjh5OGFlRS84eWFLdG9aalRIaExKMXp3V2M1ZWZZdXF2dVpzOWU0UjMwVUF1RGdTb3dHZ1hkSERXNFFDa3Z1Si83ampWekFEWDNMQkE9PQo="
  WINDOWS_APP_URL : https://sparrow-release-assests-dev.s3.us-west-1.amazonaws.com/Sparrow_2.11.0_x64_en-US.msi



# secrets:
#   PORT: "9000"
#   APP_ENV: "DEV"
#   APP_URL: "http://localhost"
#   JWT_SECRET_KEY: "webtoken-secret-key"
#   JWT_EXPIRATION_TIME: "2400"
#   # DB_URL: "mongodb://root:THlILUCAYD@sparrow-mongodb.sparrow-dev.svc.cluster.local/"
#   DB_URL: "mongodb://root:NFaBUVIvqj@my-mongodb.sparrow-test.svc.cluster.local/"
#   GOOGLE_CLIENT_ID: "google-client-id"
#   GOOGLE_CLIENT_SECRET: "google-client-secret"
#   GOOGLE_APP_URL: "google-app-url"
#   LOGIN_REDIRECT_URL: "login-redirect-url"
#   GOOGLE_ACCESS_TYPE: "google-access-type"
#   EMAIL_VALIDATION_CODE_EXPIRY_TIME: ""
#   # KAFKA_BROKER: "my-kafka-0.my-kafka-headless.sparrow-dev.svc.cluster.local:9092"
#   KAFKA_BROKER: "my-kafka.sparrow-test.svc.cluster.local:9092"
#   SMTP_SENDER_EMAIL: ""
#   SMTP_SENDER_PASSWORD: ""
#   SMTP_MAIL_HOST: ""
#   SMTP_MAIL_PORT: ""
#   SMTP_MAIL_SECURE: ""
#   SMTP_USER_NAME: ""
#   REFRESH_TOKEN_SECRET_KEY: "refresh-token-secret"
#   REFRESH_TOKEN_EXPIRATION_TIME: "604800"
#   REFRESH_TOKEN_MAX_LIMIT: "50"
#   APP_UPDATE_AVAILABLE: "true"
#   APP_VERSION: ""
#   WINDOWS_APP_SIGNATURE: ""
#   WINDOWS_APP_URL: ""
#   MAC_APPLE_SILICON_APP_SIGNATURE: ""
#   MAC_APPLE_SILICON_APP_URL: ""
#   MAC_INTEL_APP_SIGNATURE: ""
#   MAC_INTEL_APP_URL: ""
#   SPARROW_EMAIL: "sparrow@example.com"  
#   AZURE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=sparrowassets;AccountKey=N7I6yZV7qV8J1B2UZTCKXGgPo6hI5VVbPJDk6Z4oeuBzITguuRbTtzAiiC+FzRPhYUa5JCkNTCfw+AStM8jPRQ==;EndpointSuffix=core.windows.net"
#   AZURE_INSIGHTS_CONNECTION_STRING: "InstrumentationKey=a1a41bff-dd46-494c-8da5-16deca5daf32;IngestionEndpoint=https://centralindia-0.in.applicationinsights.azure.com/;LiveEndpoint=https://centralindia.livediagnostics.monitor.azure.com/;ApplicationId=79949c18-deba-4d2e-8ab5-00c1f2496b56"
#   FEEDBACK_BLOB_CONTAINER: ""
#   AZURE_OPENAI_ENDPOINT: ""
#   AZURE_OPENAI_API_KEY: ""
#   AZURE_OPENAI_DEPLOYMENT: ""
#   AZURE_OPENAI_API_VERSION: ""
#   AZURE_OPENAI_MAX_TOKENS: "1000"
#   AZURE_OPENAI_MONTHLY_TOKEN_LIMIT: "500"
#   HUBSPOT_BASEURL: ""
#   HUBSPOT_INTEGRATION_ENABLED: ""
#   HUBSPOT_PORTALID: ""
#   HUBSPOT_FORMID: ""