apiVersion: v1
kind: Secret
metadata:
  name: sparrow-api-secret
  labels:
    {{- include "sparrow-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
